apiVersion: apps/v1
kind: Deployment
metadata:
  name: wpweb-deployment
spec:
  replicas: 1 # tells deployment to run 1 pods matching the template
  selector:
    matchLabels:
      app: wpweb-deployment
  template:
    metadata:
      labels:
        app: wpweb-deployment
    spec:
      imagePullSecrets:
      - name: gcr-json-key 
      containers:
      - name: wpweb-deployment
        image: gcr.io/kubernetes-learning-praveen/wordpress:1.0.0
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: wpdb-service
        - name: WORDPRESS_DB_NAME
          value: wpdb
        - name: WORDPRESS_DB_USER
          value: wpuser
        - name: WORDPRESS_DB_PASSWORD
          value: wppass_789
